name: Generate JSON from Main and Store in Browser Branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-and-store-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Fetch Python script and modules from browser branch
        run: |
          # 只fetch browser分支的最近一次提交
          git fetch --depth=1 origin browser:browser
          # 切换到本地 browser 分支
          git checkout browser
          # 复制所需内容到上层目录
          cp -r ./utils ../utils
          cp ./generate_json.py ../generate_json.py

      - name: Switch back to main branch
        run: git checkout main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run Python script
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: python ../generate_json.py

      - name: Verify JSON file
        run: |
          if [ ! -f ./files.json ]; then
            echo "[Error] files.json 未生成！"
            exit 1
          fi

      - name: Temporarily move JSON file
        run: mv ./files.json ../temp_files.json

      - name: Checkout browser branch
        run: git checkout browser

      - name: Commit and push JSON file to browser branch
        run: |
          mv ../temp_files.json ./files.json
          git add ./files.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update files.json based on main branch" || echo "No changes to commit."
          git push origin browser
