name: Generate JSON from Main and Store in Browser Branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-and-store-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Python script and modules from browser branch
        run: |
          git fetch origin browser:browser
          git checkout browser
          cp -r ./utils ../utils
          cp ./generate_json.py ../generate_json.py

      - name: Switch back to main branch
        run: |
          git checkout main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install --upgrade pip

      # 生成 files.json
      - name: Run Python script
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python ../generate_json.py

      - name: Verify JSON file
        run: |
          if [ ! -f ./files.json ]; then
            echo "[Error] files.json 未生成！"
            exit 1
          fi

      # 先把 files.json 移走，以免后面 checkout browser 时冲突
      - name: Temporarily move JSON file
        run: |
          mv ./files.json ../temp_files.json

      - name: Checkout browser branch
        run: |
          git checkout browser

      # 把文件再移回来，添加并提交
      - name: Commit and push JSON file to browser branch
        run: |
          mv ../temp_files.json ./files.json
          git add ./files.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update files.json based on main branch" || echo "No changes to commit."
          git push origin browser
